<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-RP61NQ22" failures="4" tests="8" name="TestRunner-2" time="1.478" errors="0" timestamp="2023-09-27T11:17:14 IST">
  <testcase classname="com.TestNg.ExecutionOrderTest" name="test1" time="0.001"/>
  <testcase classname="com.TestNg.ExecutionOrderTest" name="test2" time="0.001"/>
  <testcase classname="com.TestNg.HardAssertionTest" name="hardAssert1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [I] but found [S]">
      <![CDATA[java.lang.AssertionError: expected [I] but found [S]
at com.TestNg.HardAssertionTest.hardAssert1(HardAssertionTest.java:16)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- hardAssert1 -->
  <testcase classname="com.TestNg.HardAssertionTest" name="hardAssert2" time="0.002">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.TestNg.HardAssertionTest.hardAssert2(HardAssertionTest.java:24)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- hardAssert2 -->
  <testcase classname="com.TestNg.HardAssertionTest" name="hardAssert3" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.TestNg.HardAssertionTest.hardAssert3(HardAssertionTest.java:31)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- hardAssert3 -->
  <testcase classname="com.TestNg.HardAssertionTest" name="hardAssert4" time="0.002"/>
  <testcase classname="com.TestNg.HardAssertionTest" name="hardAssert5" time="0.002">
    <failure type="java.lang.AssertionError" message="Hard assert failings">
      <![CDATA[java.lang.AssertionError: Hard assert failings
at com.TestNg.HardAssertionTest.hardAssert5(HardAssertionTest.java:45)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- hardAssert5 -->
  <testcase classname="com.TestNg.HardAssertionTest" name="hardAssert6" time="0.003"/>
</testsuite> <!-- TestRunner-2 -->
